#!/bin/bash

echo "🔧 CLEAR SESSION AND TEST NEW USERS"
echo "===================================="
echo ""

echo "📋 INSTRUCTIONS TO CLEAR YOUR BROWSER SESSION:"
echo ""
echo "1. Open your browser (Chrome/Safari/Firefox)"
echo "2. Go to your application: http://localhost:3000"
echo "3. Open Developer Tools (F12 or Cmd+Option+I)"
echo "4. Go to Application/Storage tab"
echo "5. Click on 'Local Storage' → 'http://localhost:3000'"
echo "6. Find and DELETE these keys:"
echo "   - token"
echo "   - user"
echo "   - userRole"
echo "   - userId"
echo "   Or simply click 'Clear All' for localStorage"
echo "7. Refresh the page (Cmd+R or F5)"
echo ""

echo "✅ NEW USER ACCOUNTS TO TEST:"
echo "=========================="
echo "| Role       | Email                  | Password    |"
echo "|------------|------------------------|-------------|"
echo "| ADMIN      | admin@rsud.id          | password123 |"
echo "| STAFF      | staff1@rsud.id         | password123 |"
echo "| STAFF      | staff2@rsud.id         | password123 |"
echo "| PERAWAT    | perawat1@rsud.id       | password123 |"
echo "| PERAWAT    | perawat2@rsud.id       | password123 |"
echo "| SUPERVISOR | supervisor1@rsud.id    | password123 |"
echo "| SUPERVISOR | supervisor2@rsud.id    | password123 |"
echo ""

echo "🚀 SERVERS STATUS:"
echo "=================="
echo "✅ Backend:  http://localhost:3001 - RUNNING"
echo "✅ Frontend: http://localhost:3000 - RUNNING"
echo "✅ Database: Reset with new seed structure"
echo ""

echo "⚡ QUICK TEST:"
echo "============="
echo "1. Clear localStorage as instructed above"
echo "2. Go to: http://localhost:3000"
echo "3. Try logging in with: admin@rsud.id / password123"
echo "4. You should see the dashboard with no session errors"
echo ""

echo "🔍 IF ISSUES PERSIST:"
echo "===================="
echo "1. Check browser console for errors"
echo "2. Verify backend is responding: curl http://localhost:3001"
echo "3. Check that InvalidTokenHandler is working (should auto-logout on invalid tokens)"
echo ""

echo "Done! Ready to test the new user structure. 🎉"
