// Enum lokasi shift yang sesuai dengan Prisma schema
export const LOKASI_SHIFT_ENUM = {
  GEDUNG_ADMINISTRASI: 'GEDUNG_ADMINISTRASI',
  RAWAT_JALAN: 'RAWAT_JALAN',
  RAWAT_INAP: 'RAWAT_INAP',
  GAWAT_DARURAT: 'GAWAT_DARURAT',
  LABORATORIUM: 'LABORATORIUM',
  FARMASI: 'FARMASI',
  RADIOLOGI: 'RADIOLOGI',
  GIZI: 'GIZI',
  KEAMANAN: 'KEAMANAN',
  LAUNDRY: 'LAUNDRY',
  CLEANING_SERVICE: 'CLEANING_SERVICE',
  SUPIR: 'SUPIR',
  ICU: 'ICU',
  NICU: 'NICU',
  HEMODIALISA: 'HEMODIALISA',
  FISIOTERAPI: 'FISIOTERAPI',
  KAMAR_OPERASI: 'KAMAR_OPERASI',
  RECOVERY_ROOM: 'RECOVERY_ROOM',
  EMERGENCY_ROOM: 'EMERGENCY_ROOM',
} as const;

export type LokasiShiftType = typeof LOKASI_SHIFT_ENUM[keyof typeof LOKASI_SHIFT_ENUM];

// Mapping untuk display name
export const LOKASI_SHIFT_DISPLAY_NAMES = {
  [LOKASI_SHIFT_ENUM.GEDUNG_ADMINISTRASI]: 'Gedung Administrasi',
  [LOKASI_SHIFT_ENUM.RAWAT_JALAN]: 'Rawat Jalan',
  [LOKASI_SHIFT_ENUM.RAWAT_INAP]: 'Rawat Inap (3 Shift)',
  [LOKASI_SHIFT_ENUM.GAWAT_DARURAT]: 'Gawat Darurat (3 Shift)',
  [LOKASI_SHIFT_ENUM.LABORATORIUM]: 'Laboratorium (2 Shift)',
  [LOKASI_SHIFT_ENUM.FARMASI]: 'Farmasi (2 Shift)',
  [LOKASI_SHIFT_ENUM.RADIOLOGI]: 'Radiologi (2 Shift)',
  [LOKASI_SHIFT_ENUM.GIZI]: 'Gizi (2 Shift)',
  [LOKASI_SHIFT_ENUM.KEAMANAN]: 'Keamanan (2 Shift)',
  [LOKASI_SHIFT_ENUM.LAUNDRY]: 'Laundry',
  [LOKASI_SHIFT_ENUM.CLEANING_SERVICE]: 'Cleaning Service',
  [LOKASI_SHIFT_ENUM.SUPIR]: 'Supir (2 Shift)',
  [LOKASI_SHIFT_ENUM.ICU]: 'ICU',
  [LOKASI_SHIFT_ENUM.NICU]: 'NICU',
  [LOKASI_SHIFT_ENUM.HEMODIALISA]: 'Hemodialisa',
  [LOKASI_SHIFT_ENUM.FISIOTERAPI]: 'Fisioterapi',
  [LOKASI_SHIFT_ENUM.KAMAR_OPERASI]: 'Kamar Operasi',
  [LOKASI_SHIFT_ENUM.RECOVERY_ROOM]: 'Recovery Room',
  [LOKASI_SHIFT_ENUM.EMERGENCY_ROOM]: 'Emergency Room',
} as const;

// Array untuk dropdown options
export const LOKASI_SHIFT_OPTIONS = Object.entries(LOKASI_SHIFT_DISPLAY_NAMES).map(([value, label]) => ({
  value,
  label,
}));
